# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Woravit Ariyakunatorn
title: DevOps Engineer
email: golf@wariyakunatorn.com
# email_title: Email (Email title override)
# phone: Your phone number (optional)
# phone_title: Phone (Phone title override)
website: https://wariyakunatorn.com
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: jekyllrb
github_username:  wariyakunatorn
#stackoverflow_username: "00000001"
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
linkedin_username: wariyakunatorn
#xing_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#orcid_username: 0000-0000-0000-0000
#googlescholar_username: D847cGsAAAAJ

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hello, I'm Woravit Ariyakunatorn. Here's a bit about me:

  - With over a decade in IT, I'm currently immersed in the fascinating world of DevOps.
  - I thrive in the Agile methodology, fostering collaboration between development and operations teams.
  - My expertise covers a range of DevOps aspects, from automation to continuous integration, delivery, and infrastructure as code.
  - Beyond the tech scene, I enjoy fishing, outdoor activities, and staying abreast of the latest trends and best practices

content:
  # - title: Projects # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       border: weak  # Value of `weak` will display a weak border below this item. # Any 
  #                     # other value (or no value) means no border will be displayed
  #       title: Project name
  #       link: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #       link_text: Link Text
  #       additional_links:
  #         - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #           icon: fab fa-github
  #           url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #         - title:  Github page for project (eg. sproogen/modern-resume-theme)
  #           icon: fab fa-github
  #           url: Link to project (eg. sproogen.github.io/modern-resume-theme)(optional)
  #       quote: >
  #         Short overview of the project (optional)
  #       description: | # this will include new lines to allow paragraphs
  #         Description about the work on/with the project
- title: Experience
  layout: list
  content:
    - layout: left
      title: Allianz Technology Thailand
      sub_title: Principal DevOps Engineer
      caption: 2021 - Present
      description: |
        - Led a DevOps engineering team, providing technical guidance and leadership for successful product delivery.
        - Collaborated with 50+ internal stakeholders, improving product delivery processes.
        - Proficient in cloud computing, automation, CI/CD, microservices, security, and more.
        - Managed recruitment, onboarding, and training of DevOps engineers.
        - Fostered a culture of innovation, continuous improvement, and collaboration.

    - layout: left
      title: SES Satellites
      sub_title: Infrastructure Engineer
      caption: 2016 - 2020
      description: |
        - Led design, implementation, and maintenance of global system solutions.
        - Managed infrastructure for 50+ locations worldwide.
        - Led and managed multiple projects, ensuring on-time and within-budget execution.
        - Accountable for design, monitoring, and management of signal distribution components.
        - Experienced in live video streaming, transcoding, and playback.

    - layout: left
      title: Allianz Technology Thailand
      sub_title: Senior Infrastructure Engineer
      caption: 2014 - 2015
      description: |
        - Maintained system security and supported day-to-day server operations.
        - Proactively monitored system performance and provided guidance to less experienced staff.
        - Managed highly available infrastructure, including Windows Servers, VMware, and more.
        - Facilitated cross-team collaboration.

    - layout: left
      title: Toyota Technical Center Australia
      sub_title: Systems Engineer
      caption: 2013
      description: |
        - Installed and maintained a wide range of IT equipment.
        - Expertise in installing and configuring computer hardware, software, and systems.
        - Extensive experience in software installation and troubleshooting for CAD engineering.

    - layout: left
      title: Toyota Tsusho Network Integration Thailand
      sub_title: Systems Engineer
      caption: 2011 - 2012
      description: |
        - Oversaw and coordinated projects from inception to completion.
        - Managed project timelines and addressed issues during implementation.
        - Troubleshooted and resolved complex technical problems.
        - Expertise in system engineering for successful project implementations.

- title: Education
  layout: list
  content:
    - layout: left
      title: Mahidol University, Thailand
      sub_title: Bachelor's Degree in Computer Science
      caption: 2011
      #description: |
      #  Description of the qualification.

- title: Certification
  layout: list
  content:
    - layout: left
      #title: CKA - Certified Kubernetes Administrator
      caption: 2023
      description: |
        CKA - Certified Kubernetes Administrator
    - layout: left
      #title: AWS Certified Solutions Architect – Associate
      caption: 2022
      description: |
        Description of the qualification.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
